const fs = require('fs'); 
let code = fs.readFileSync('src/components/exam/AnswerOptionList.tsx', 'utf8'); 
code = code.replace('isAnswered: boolean;', 'isAnswered: boolean;\n  isTimedMode?: boolean;'); 
code = code.replace('isAnswered,', 'isAnswered,\n  isTimedMode,'); 
code = code.replace('if (isAnswered) {', 'if (isAnswered && !isTimedMode) {'); 
code = code.replace('{isAnswered ? (\n              <div', '{isAnswered && !isTimedMode ? (\n              <div'); 
code = code.replace('isSelected && !isAnswered ?', 'isSelected && (!isAnswered || isTimedMode) ?'); 
code = code.replace('isAnswered && isSelected && option.is_correct', 'isAnswered && !isTimedMode && isSelected && option.is_correct'); 
code = code.replace('} \}', '} \}'); 
code = code.replace('{isAnswered ? (\n                  <span className=\"rounded-full bg-[#7f8790]', '{isAnswered && !isTimedMode ? (\n                  <span className=\"rounded-full bg-[#7f8790]'); 
fs.writeFileSync('src/components/exam/AnswerOptionList.tsx', code);
