-- Canonical topic identity and Study Plan backend.
-- Topic identity is bank + normalized topic name. Category is display/priority metadata,
-- never part of identity, so legacy category spelling variants do not split one topic.

CREATE TABLE IF NOT EXISTS public.content_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_bank_id BIGINT NOT NULL REFERENCES public.question_banks(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    normalized_name TEXT GENERATED ALWAYS AS (lower(btrim(name))) STORED,
    category TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE (question_bank_id, normalized_name),
    UNIQUE (question_bank_id, id)
);

CREATE INDEX IF NOT EXISTS idx_content_topics_bank_category_order
    ON public.content_topics(question_bank_id, category, display_order, name);

CREATE TABLE IF NOT EXISTS public.question_topics (
    question_bank_id BIGINT NOT NULL REFERENCES public.question_banks(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    topic_id BIGINT NOT NULL REFERENCES public.content_topics(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (question_bank_id, question_id, topic_id),
    UNIQUE (question_bank_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_question_topics_topic_question
    ON public.question_topics(topic_id, question_id);

CREATE TABLE IF NOT EXISTS public.topic_library_articles (
    question_bank_id BIGINT NOT NULL REFERENCES public.question_banks(id) ON DELETE CASCADE,
    topic_id BIGINT NOT NULL REFERENCES public.content_topics(id) ON DELETE CASCADE,
    article_id TEXT NOT NULL REFERENCES public.library_articles(id) ON DELETE CASCADE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (question_bank_id, topic_id, article_id),
    UNIQUE (question_bank_id, article_id)
);

CREATE INDEX IF NOT EXISTS idx_topic_library_articles_primary
    ON public.topic_library_articles(question_bank_id, topic_id, is_primary DESC, display_order, article_id);

ALTER TABLE public.content_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_topics FORCE ROW LEVEL SECURITY;
ALTER TABLE public.question_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_topics FORCE ROW LEVEL SECURITY;
ALTER TABLE public.topic_library_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topic_library_articles FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.content_topics FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.question_topics FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.topic_library_articles FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.refresh_content_topic_links(p_bank_id BIGINT DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_topics INTEGER := 0;
    v_questions INTEGER := 0;
    v_articles INTEGER := 0;
BEGIN
    IF p_bank_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.question_banks qb WHERE qb.id = p_bank_id
    ) THEN
        RAISE EXCEPTION 'STUDY_PLAN_BANK_NOT_FOUND';
    END IF;

    WITH candidates AS (
        SELECT
            qbq.question_bank_id,
            btrim(q.topic) AS topic_name,
            NULLIF(btrim(q.category), '') AS category,
            1 AS source_priority,
            0 AS source_order
        FROM public.question_bank_questions qbq
        JOIN public.questions q ON q.id = qbq.question_id
        WHERE q.topic IS NOT NULL
          AND btrim(q.topic) <> ''
          AND (p_bank_id IS NULL OR qbq.question_bank_id = p_bank_id)

        UNION ALL

        SELECT
            qbla.question_bank_id,
            btrim(COALESCE(NULLIF(la.topic, ''), la.name)) AS topic_name,
            NULLIF(btrim(la.category), '') AS category,
            0 AS source_priority,
            qbla.display_order AS source_order
        FROM public.question_bank_library_articles qbla
        JOIN public.library_articles la ON la.id = qbla.article_id
        WHERE btrim(COALESCE(NULLIF(la.topic, ''), la.name)) <> ''
          AND (p_bank_id IS NULL OR qbla.question_bank_id = p_bank_id)
    ), ranked AS (
        SELECT
            question_bank_id,
            topic_name,
            (array_agg(category ORDER BY source_priority, source_order, topic_name)
                FILTER (WHERE category IS NOT NULL))[1] AS category,
            MIN(source_order) AS display_order
        FROM candidates
        GROUP BY question_bank_id, lower(btrim(topic_name)), topic_name
    ), deduped AS (
        SELECT DISTINCT ON (question_bank_id, lower(btrim(topic_name)))
            question_bank_id,
            topic_name,
            category,
            display_order
        FROM ranked
        ORDER BY question_bank_id, lower(btrim(topic_name)), display_order, topic_name
    )
    INSERT INTO public.content_topics (
        question_bank_id, name, category, display_order, updated_at
    )
    SELECT
        question_bank_id,
        topic_name,
        category,
        display_order,
        timezone('utc'::text, now())
    FROM deduped
    ON CONFLICT (question_bank_id, normalized_name)
    DO UPDATE SET
        name = EXCLUDED.name,
        category = COALESCE(EXCLUDED.category, public.content_topics.category),
        display_order = LEAST(public.content_topics.display_order, EXCLUDED.display_order),
        updated_at = timezone('utc'::text, now());

    GET DIAGNOSTICS v_topics = ROW_COUNT;

    DELETE FROM public.question_topics qt
    WHERE p_bank_id IS NULL OR qt.question_bank_id = p_bank_id;

    INSERT INTO public.question_topics (question_bank_id, question_id, topic_id)
    SELECT
        qbq.question_bank_id,
        q.id,
        ct.id
    FROM public.question_bank_questions qbq
    JOIN public.questions q ON q.id = qbq.question_id
    JOIN public.content_topics ct
      ON ct.question_bank_id = qbq.question_bank_id
     AND ct.normalized_name = lower(btrim(q.topic))
    WHERE q.topic IS NOT NULL
      AND btrim(q.topic) <> ''
      AND (p_bank_id IS NULL OR qbq.question_bank_id = p_bank_id)
    ON CONFLICT (question_bank_id, question_id)
    DO UPDATE SET topic_id = EXCLUDED.topic_id;

    GET DIAGNOSTICS v_questions = ROW_COUNT;

    DELETE FROM public.topic_library_articles tla
    WHERE p_bank_id IS NULL OR tla.question_bank_id = p_bank_id;

    WITH linked AS (
        SELECT
            qbla.question_bank_id,
            ct.id AS topic_id,
            la.id AS article_id,
            qbla.display_order,
            row_number() OVER (
                PARTITION BY qbla.question_bank_id, ct.id
                ORDER BY qbla.display_order, la.id
            ) AS topic_rank
        FROM public.question_bank_library_articles qbla
        JOIN public.library_articles la ON la.id = qbla.article_id
        JOIN public.content_topics ct
          ON ct.question_bank_id = qbla.question_bank_id
         AND ct.normalized_name = lower(btrim(COALESCE(NULLIF(la.topic, ''), la.name)))
        WHERE (p_bank_id IS NULL OR qbla.question_bank_id = p_bank_id)
    )
    INSERT INTO public.topic_library_articles (
        question_bank_id, topic_id, article_id, is_primary, display_order
    )
    SELECT
        question_bank_id,
        topic_id,
        article_id,
        topic_rank = 1,
        display_order
    FROM linked
    ON CONFLICT (question_bank_id, topic_id, article_id)
    DO UPDATE SET
        is_primary = EXCLUDED.is_primary,
        display_order = EXCLUDED.display_order;

    GET DIAGNOSTICS v_articles = ROW_COUNT;

    RETURN jsonb_build_object(
        'topics_touched', v_topics,
        'question_links', v_questions,
        'article_links', v_articles
    );
END;
$$;

REVOKE ALL ON FUNCTION public.refresh_content_topic_links(BIGINT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_content_topic_links(BIGINT) TO service_role;

-- Keep canonical topic links current at the same explicit content-refresh boundary used by imports.
CREATE OR REPLACE FUNCTION public.content_manager_refresh_counts()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_topic_refresh JSONB;
BEGIN
    PERFORM public.refresh_bank_question_stats();
    REFRESH MATERIALIZED VIEW public.question_bank_topic_counts;
    v_topic_refresh := public.refresh_content_topic_links(NULL);

    RETURN jsonb_build_object(
        'refreshed', TRUE,
        'refreshed_at', clock_timestamp(),
        'canonical_topics', v_topic_refresh
    );
END;
$$;

REVOKE ALL ON FUNCTION public.content_manager_refresh_counts() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.content_manager_refresh_counts() TO service_role;

CREATE TABLE IF NOT EXISTS public.study_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    question_bank_id BIGINT NOT NULL REFERENCES public.question_banks(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    exam_date DATE NOT NULL,
    study_weekdays SMALLINT[] NOT NULL DEFAULT ARRAY[1,2,3,4,5]::SMALLINT[],
    missed_strategy TEXT NOT NULL DEFAULT 'redistribute'
        CHECK (missed_strategy IN ('next_free_day', 'redistribute')),
    reduced_load_factor NUMERIC(4,3) NOT NULL DEFAULT 0.5
        CHECK (reduced_load_factor > 0 AND reduced_load_factor <= 1),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CHECK (exam_date > start_date),
    CHECK (cardinality(study_weekdays) > 0),
    CHECK (study_weekdays <@ ARRAY[0,1,2,3,4,5,6]::SMALLINT[])
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_study_plans_one_active
    ON public.study_plans(user_id, question_bank_id)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_study_plans_user_bank_status
    ON public.study_plans(user_id, question_bank_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.study_plan_category_priorities (
    plan_id UUID NOT NULL REFERENCES public.study_plans(id) ON DELETE CASCADE,
    category_name TEXT NOT NULL,
    priority INTEGER NOT NULL CHECK (priority >= 0),
    PRIMARY KEY (plan_id, category_name),
    UNIQUE (plan_id, priority)
);

CREATE TABLE IF NOT EXISTS public.study_plan_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id UUID NOT NULL REFERENCES public.study_plans(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('pause', 'reduced')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_study_plan_periods_plan_dates
    ON public.study_plan_periods(plan_id, start_date, end_date, mode);

CREATE TABLE IF NOT EXISTS public.study_plan_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id UUID NOT NULL REFERENCES public.study_plans(id) ON DELETE CASCADE,
    topic_id BIGINT NOT NULL REFERENCES public.content_topics(id) ON DELETE RESTRICT,
    scheduled_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE (plan_id, topic_id),
    CHECK ((status = 'completed' AND completed_at IS NOT NULL)
        OR (status = 'pending' AND completed_at IS NULL))
);
CREATE INDEX IF NOT EXISTS idx_study_plan_tasks_plan_date_status
    ON public.study_plan_tasks(plan_id, scheduled_date, status);

CREATE TABLE IF NOT EXISTS public.study_plan_session_links (
    task_id BIGINT NOT NULL REFERENCES public.study_plan_tasks(id) ON DELETE CASCADE,
    session_id UUID NOT NULL REFERENCES public.test_sessions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (task_id, session_id),
    UNIQUE (session_id)
);

ALTER TABLE public.study_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_plans FORCE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_category_priorities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_category_priorities FORCE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_periods FORCE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_tasks FORCE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_session_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_plan_session_links FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.study_plans FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.study_plan_category_priorities FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.study_plan_periods FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.study_plan_tasks FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.study_plan_session_links FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.study_plans TO authenticated;
GRANT SELECT ON TABLE public.study_plan_category_priorities TO authenticated;
GRANT SELECT ON TABLE public.study_plan_periods TO authenticated;
GRANT SELECT ON TABLE public.study_plan_tasks TO authenticated;
GRANT SELECT ON TABLE public.study_plan_session_links TO authenticated;

CREATE POLICY study_plans_owner_select ON public.study_plans
FOR SELECT TO authenticated
USING (user_id = auth.uid());

CREATE POLICY study_plan_priorities_owner_select ON public.study_plan_category_priorities
FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.study_plans sp
    WHERE sp.id = plan_id AND sp.user_id = auth.uid()
));

CREATE POLICY study_plan_periods_owner_select ON public.study_plan_periods
FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.study_plans sp
    WHERE sp.id = plan_id AND sp.user_id = auth.uid()
));

CREATE POLICY study_plan_tasks_owner_select ON public.study_plan_tasks
FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.study_plans sp
    WHERE sp.id = plan_id AND sp.user_id = auth.uid()
));

CREATE POLICY study_plan_links_owner_select ON public.study_plan_session_links
FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1
    FROM public.study_plan_tasks spt
    JOIN public.study_plans sp ON sp.id = spt.plan_id
    WHERE spt.id = task_id AND sp.user_id = auth.uid()
));

CREATE OR REPLACE FUNCTION public.schedule_study_plan_pending(
    p_plan_id UUID,
    p_from_date DATE DEFAULT NULL
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_plan public.study_plans%ROWTYPE;
    v_first_date DATE;
    v_unfinished INTEGER;
    v_eligible INTEGER;
    v_scheduled INTEGER := 0;
BEGIN
    SELECT * INTO v_plan FROM public.study_plans WHERE id = p_plan_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'STUDY_PLAN_NOT_FOUND';
    END IF;

    v_first_date := GREATEST(v_plan.start_date, COALESCE(p_from_date, v_plan.start_date));

    SELECT COUNT(*)::INTEGER INTO v_unfinished
    FROM (
        SELECT DISTINCT qt.topic_id
        FROM public.question_topics qt
        WHERE qt.question_bank_id = v_plan.question_bank_id
          AND NOT EXISTS (
              SELECT 1 FROM public.study_plan_tasks done
              WHERE done.plan_id = v_plan.id
                AND done.topic_id = qt.topic_id
                AND done.status = 'completed'
          )
    ) unfinished;

    IF v_unfinished = 0 THEN
        RETURN 0;
    END IF;

    SELECT COUNT(*)::INTEGER INTO v_eligible
    FROM generate_series(v_first_date, v_plan.exam_date - 1, interval '1 day') d
    WHERE extract(dow FROM d)::SMALLINT = ANY(v_plan.study_weekdays)
      AND NOT EXISTS (
          SELECT 1 FROM public.study_plan_periods spp
          WHERE spp.plan_id = v_plan.id
            AND spp.mode = 'pause'
            AND d::DATE BETWEEN spp.start_date AND spp.end_date
      );

    IF v_eligible = 0 THEN
        RAISE EXCEPTION 'STUDY_PLAN_NO_ELIGIBLE_DAYS';
    END IF;

    WITH unfinished AS (
        SELECT
            ct.id AS topic_id,
            row_number() OVER (
                ORDER BY
                    COALESCE(spp.priority, 100000),
                    COALESCE(ct.category, ''),
                    ct.display_order,
                    ct.name,
                    ct.id
            ) AS rn,
            count(*) OVER () AS total_topics
        FROM public.content_topics ct
        JOIN (
            SELECT DISTINCT topic_id
            FROM public.question_topics
            WHERE question_bank_id = v_plan.question_bank_id
        ) active_topics ON active_topics.topic_id = ct.id
        LEFT JOIN public.study_plan_category_priorities spp
          ON spp.plan_id = v_plan.id
         AND spp.category_name = COALESCE(ct.category, 'General')
        WHERE ct.question_bank_id = v_plan.question_bank_id
          AND NOT EXISTS (
              SELECT 1 FROM public.study_plan_tasks done
              WHERE done.plan_id = v_plan.id
                AND done.topic_id = ct.id
                AND done.status = 'completed'
          )
    ), eligible_days AS (
        SELECT
            d::DATE AS schedule_date,
            CASE
                WHEN EXISTS (
                    SELECT 1 FROM public.study_plan_periods spp
                    WHERE spp.plan_id = v_plan.id
                      AND spp.mode = 'reduced'
                      AND d::DATE BETWEEN spp.start_date AND spp.end_date
                ) THEN v_plan.reduced_load_factor
                ELSE 1::NUMERIC
            END AS weight
        FROM generate_series(v_first_date, v_plan.exam_date - 1, interval '1 day') d
        WHERE extract(dow FROM d)::SMALLINT = ANY(v_plan.study_weekdays)
          AND NOT EXISTS (
              SELECT 1 FROM public.study_plan_periods spp
              WHERE spp.plan_id = v_plan.id
                AND spp.mode = 'pause'
                AND d::DATE BETWEEN spp.start_date AND spp.end_date
          )
    ), weighted_days AS (
        SELECT
            schedule_date,
            weight,
            sum(weight) OVER (ORDER BY schedule_date) AS cumulative_weight,
            sum(weight) OVER () AS total_weight
        FROM eligible_days
    ), assignments AS (
        SELECT
            u.topic_id,
            (
                SELECT wd.schedule_date
                FROM weighted_days wd
                WHERE wd.cumulative_weight >=
                    (((u.rn::NUMERIC - 0.5) / u.total_topics::NUMERIC) * wd.total_weight)
                ORDER BY wd.schedule_date
                LIMIT 1
            ) AS scheduled_date
        FROM unfinished u
    )
    INSERT INTO public.study_plan_tasks (
        plan_id, topic_id, scheduled_date, status, completed_at, updated_at
    )
    SELECT
        v_plan.id,
        a.topic_id,
        a.scheduled_date,
        'pending',
        NULL,
        timezone('utc'::text, now())
    FROM assignments a
    WHERE a.scheduled_date IS NOT NULL
    ON CONFLICT (plan_id, topic_id)
    DO UPDATE SET
        scheduled_date = EXCLUDED.scheduled_date,
        updated_at = timezone('utc'::text, now())
    WHERE public.study_plan_tasks.status = 'pending';

    GET DIAGNOSTICS v_scheduled = ROW_COUNT;
    RETURN v_scheduled;
END;
$$;

REVOKE ALL ON FUNCTION public.schedule_study_plan_pending(UUID, DATE) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_study_plan_catalog(p_bank_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_result JSONB;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;
    IF NOT public.can_access_question_bank(p_bank_id) THEN
        RAISE EXCEPTION 'Question bank access denied';
    END IF;

    SELECT jsonb_build_object(
        'bank_id', p_bank_id,
        'topic_count', COUNT(*),
        'categories', COALESCE(
            jsonb_agg(category_payload ORDER BY category_name),
            '[]'::jsonb
        )
    )
    INTO v_result
    FROM (
        SELECT
            COALESCE(ct.category, 'General') AS category_name,
            jsonb_build_object(
                'name', COALESCE(ct.category, 'General'),
                'topic_count', COUNT(*),
                'topics', jsonb_agg(
                    jsonb_build_object(
                        'id', ct.id,
                        'name', ct.name,
                        'question_count', question_count,
                        'article_id', article_id
                    ) ORDER BY ct.display_order, ct.name
                )
            ) AS category_payload
        FROM public.content_topics ct
        JOIN LATERAL (
            SELECT COUNT(*)::INTEGER AS question_count
            FROM public.question_topics qt
            WHERE qt.question_bank_id = p_bank_id
              AND qt.topic_id = ct.id
        ) qc ON qc.question_count > 0
        LEFT JOIN LATERAL (
            SELECT tla.article_id
            FROM public.topic_library_articles tla
            WHERE tla.question_bank_id = p_bank_id
              AND tla.topic_id = ct.id
            ORDER BY tla.is_primary DESC, tla.display_order, tla.article_id
            LIMIT 1
        ) article ON TRUE
        CROSS JOIN LATERAL (SELECT qc.question_count, article.article_id) values_row
        WHERE ct.question_bank_id = p_bank_id
        GROUP BY COALESCE(ct.category, 'General')
    ) grouped;

    RETURN COALESCE(v_result, jsonb_build_object(
        'bank_id', p_bank_id,
        'topic_count', 0,
        'categories', '[]'::jsonb
    ));
END;
$$;

REVOKE ALL ON FUNCTION public.get_study_plan_catalog(BIGINT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_study_plan_catalog(BIGINT) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.create_study_plan(
    p_bank_id BIGINT,
    p_start_date DATE,
    p_exam_date DATE,
    p_study_weekdays SMALLINT[],
    p_missed_strategy TEXT DEFAULT 'redistribute',
    p_reduced_load_factor NUMERIC DEFAULT 0.5,
    p_periods JSONB DEFAULT '[]'::jsonb,
    p_category_priorities JSONB DEFAULT '[]'::jsonb
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_plan_id UUID;
    v_topics INTEGER;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;
    IF NOT public.can_access_question_bank(p_bank_id) THEN
        RAISE EXCEPTION 'Question bank access denied';
    END IF;
    IF p_start_date IS NULL OR p_exam_date IS NULL OR p_exam_date <= p_start_date THEN
        RAISE EXCEPTION 'STUDY_PLAN_INVALID_DATES';
    END IF;
    IF p_study_weekdays IS NULL OR cardinality(p_study_weekdays) = 0
       OR NOT (p_study_weekdays <@ ARRAY[0,1,2,3,4,5,6]::SMALLINT[]) THEN
        RAISE EXCEPTION 'STUDY_PLAN_INVALID_WEEKDAYS';
    END IF;
    IF p_missed_strategy NOT IN ('next_free_day', 'redistribute') THEN
        RAISE EXCEPTION 'STUDY_PLAN_INVALID_MISSED_STRATEGY';
    END IF;
    IF p_reduced_load_factor <= 0 OR p_reduced_load_factor > 1 THEN
        RAISE EXCEPTION 'STUDY_PLAN_INVALID_REDUCED_LOAD';
    END IF;

    SELECT COUNT(DISTINCT qt.topic_id)::INTEGER INTO v_topics
    FROM public.question_topics qt
    WHERE qt.question_bank_id = p_bank_id;
    IF v_topics = 0 THEN
        RAISE EXCEPTION 'STUDY_PLAN_NO_TOPICS';
    END IF;

    UPDATE public.study_plans
    SET status = 'archived', updated_at = timezone('utc'::text, now())
    WHERE user_id = auth.uid()
      AND question_bank_id = p_bank_id
      AND status = 'active';

    INSERT INTO public.study_plans (
        user_id, question_bank_id, start_date, exam_date, study_weekdays,
        missed_strategy, reduced_load_factor
    ) VALUES (
        auth.uid(), p_bank_id, p_start_date, p_exam_date,
        ARRAY(SELECT DISTINCT x FROM unnest(p_study_weekdays) x ORDER BY x),
        p_missed_strategy, p_reduced_load_factor
    ) RETURNING id INTO v_plan_id;

    INSERT INTO public.study_plan_periods (plan_id, start_date, end_date, mode)
    SELECT
        v_plan_id,
        (item->>'start_date')::DATE,
        (item->>'end_date')::DATE,
        item->>'mode'
    FROM jsonb_array_elements(COALESCE(p_periods, '[]'::jsonb)) item
    WHERE item->>'mode' IN ('pause', 'reduced')
      AND (item->>'start_date')::DATE <= (item->>'end_date')::DATE
      AND (item->>'end_date')::DATE >= p_start_date
      AND (item->>'start_date')::DATE < p_exam_date;

    INSERT INTO public.study_plan_category_priorities (plan_id, category_name, priority)
    SELECT
        v_plan_id,
        item->>'category',
        (item->>'priority')::INTEGER
    FROM jsonb_array_elements(COALESCE(p_category_priorities, '[]'::jsonb)) item
    WHERE COALESCE(btrim(item->>'category'), '') <> ''
    ON CONFLICT (plan_id, category_name) DO UPDATE SET priority = EXCLUDED.priority;

    PERFORM public.schedule_study_plan_pending(v_plan_id, p_start_date);
    RETURN v_plan_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_study_plan(BIGINT, DATE, DATE, SMALLINT[], TEXT, NUMERIC, JSONB, JSONB)
    FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_study_plan(BIGINT, DATE, DATE, SMALLINT[], TEXT, NUMERIC, JSONB, JSONB)
    TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.update_study_plan(
    p_plan_id UUID,
    p_start_date DATE,
    p_exam_date DATE,
    p_study_weekdays SMALLINT[],
    p_missed_strategy TEXT,
    p_reduced_load_factor NUMERIC,
    p_periods JSONB DEFAULT '[]'::jsonb,
    p_category_priorities JSONB DEFAULT '[]'::jsonb
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_plan public.study_plans%ROWTYPE;
BEGIN
    SELECT * INTO v_plan FROM public.study_plans WHERE id = p_plan_id;
    IF NOT FOUND OR v_plan.user_id <> auth.uid() OR v_plan.status <> 'active' THEN
        RAISE EXCEPTION 'STUDY_PLAN_NOT_FOUND';
    END IF;
    IF NOT public.can_access_question_bank(v_plan.question_bank_id) THEN
        RAISE EXCEPTION 'Question bank access denied';
    END IF;
    IF p_exam_date <= p_start_date OR p_study_weekdays IS NULL OR cardinality(p_study_weekdays) = 0
       OR NOT (p_study_weekdays <@ ARRAY[0,1,2,3,4,5,6]::SMALLINT[]) THEN
        RAISE EXCEPTION 'STUDY_PLAN_INVALID_SETTINGS';
    END IF;

    UPDATE public.study_plans SET
        start_date = p_start_date,
        exam_date = p_exam_date,
        study_weekdays = ARRAY(SELECT DISTINCT x FROM unnest(p_study_weekdays) x ORDER BY x),
        missed_strategy = p_missed_strategy,
        reduced_load_factor = p_reduced_load_factor,
        updated_at = timezone('utc'::text, now())
    WHERE id = p_plan_id;

    DELETE FROM public.study_plan_periods WHERE plan_id = p_plan_id;
    INSERT INTO public.study_plan_periods (plan_id, start_date, end_date, mode)
    SELECT p_plan_id, (item->>'start_date')::DATE, (item->>'end_date')::DATE, item->>'mode'
    FROM jsonb_array_elements(COALESCE(p_periods, '[]'::jsonb)) item
    WHERE item->>'mode' IN ('pause', 'reduced')
      AND (item->>'start_date')::DATE <= (item->>'end_date')::DATE;

    DELETE FROM public.study_plan_category_priorities WHERE plan_id = p_plan_id;
    INSERT INTO public.study_plan_category_priorities (plan_id, category_name, priority)
    SELECT p_plan_id, item->>'category', (item->>'priority')::INTEGER
    FROM jsonb_array_elements(COALESCE(p_category_priorities, '[]'::jsonb)) item
    WHERE COALESCE(btrim(item->>'category'), '') <> '';

    PERFORM public.schedule_study_plan_pending(
        p_plan_id,
        GREATEST(p_start_date, CURRENT_DATE)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.update_study_plan(UUID, DATE, DATE, SMALLINT[], TEXT, NUMERIC, JSONB, JSONB)
    FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_study_plan(UUID, DATE, DATE, SMALLINT[], TEXT, NUMERIC, JSONB, JSONB)
    TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.mark_study_plan_task_complete(p_task_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_bank_id BIGINT;
BEGIN
    SELECT sp.question_bank_id INTO v_bank_id
    FROM public.study_plan_tasks spt
    JOIN public.study_plans sp ON sp.id = spt.plan_id
    WHERE spt.id = p_task_id
      AND sp.user_id = auth.uid()
      AND sp.status = 'active';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'STUDY_PLAN_TASK_NOT_FOUND';
    END IF;
    IF NOT public.can_access_question_bank(v_bank_id) THEN
        RAISE EXCEPTION 'Question bank access denied';
    END IF;

    UPDATE public.study_plan_tasks
    SET
        status = 'completed',
        completed_at = COALESCE(completed_at, timezone('utc'::text, now())),
        updated_at = timezone('utc'::text, now())
    WHERE id = p_task_id;
END;
$$;

REVOKE ALL ON FUNCTION public.mark_study_plan_task_complete(BIGINT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mark_study_plan_task_complete(BIGINT) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.link_study_plan_session(p_task_id BIGINT, p_session_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_bank_id BIGINT;
BEGIN
    SELECT sp.question_bank_id INTO v_bank_id
    FROM public.study_plan_tasks spt
    JOIN public.study_plans sp ON sp.id = spt.plan_id
    WHERE spt.id = p_task_id
      AND sp.user_id = auth.uid()
      AND sp.status = 'active';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'STUDY_PLAN_TASK_NOT_FOUND';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.test_sessions ts
        WHERE ts.id = p_session_id
          AND ts.user_id = auth.uid()
          AND ts.question_bank_id = v_bank_id
    ) THEN
        RAISE EXCEPTION 'STUDY_PLAN_SESSION_MISMATCH';
    END IF;

    INSERT INTO public.study_plan_session_links(task_id, session_id)
    VALUES (p_task_id, p_session_id)
    ON CONFLICT (session_id) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.link_study_plan_session(BIGINT, UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.link_study_plan_session(BIGINT, UUID) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.rebalance_study_plan(
    p_plan_id UUID,
    p_strategy TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_plan public.study_plans%ROWTYPE;
    v_strategy TEXT;
    v_overdue INTEGER;
    v_free_days INTEGER;
    v_moved INTEGER := 0;
BEGIN
    SELECT * INTO v_plan FROM public.study_plans WHERE id = p_plan_id;
    IF NOT FOUND OR v_plan.user_id <> auth.uid() OR v_plan.status <> 'active' THEN
        RAISE EXCEPTION 'STUDY_PLAN_NOT_FOUND';
    END IF;
    IF NOT public.can_access_question_bank(v_plan.question_bank_id) THEN
        RAISE EXCEPTION 'Question bank access denied';
    END IF;

    v_strategy := COALESCE(p_strategy, v_plan.missed_strategy);
    IF v_strategy NOT IN ('next_free_day', 'redistribute') THEN
        RAISE EXCEPTION 'STUDY_PLAN_INVALID_MISSED_STRATEGY';
    END IF;

    SELECT COUNT(*)::INTEGER INTO v_overdue
    FROM public.study_plan_tasks
    WHERE plan_id = p_plan_id AND status = 'pending' AND scheduled_date < CURRENT_DATE;

    IF v_overdue = 0 THEN
        RETURN jsonb_build_object('strategy', v_strategy, 'moved', 0, 'fallback', FALSE);
    END IF;

    IF v_strategy = 'next_free_day' THEN
        SELECT COUNT(*)::INTEGER INTO v_free_days
        FROM generate_series(GREATEST(CURRENT_DATE, v_plan.start_date), v_plan.exam_date - 1, interval '1 day') d
        WHERE extract(dow FROM d)::SMALLINT = ANY(v_plan.study_weekdays)
          AND NOT EXISTS (
              SELECT 1 FROM public.study_plan_periods spp
              WHERE spp.plan_id = p_plan_id
                AND spp.mode = 'pause'
                AND d::DATE BETWEEN spp.start_date AND spp.end_date
          )
          AND NOT EXISTS (
              SELECT 1 FROM public.study_plan_tasks spt
              WHERE spt.plan_id = p_plan_id
                AND spt.scheduled_date = d::DATE
                AND spt.status = 'pending'
          );

        IF v_free_days >= v_overdue THEN
            WITH overdue AS (
                SELECT id, row_number() OVER (ORDER BY scheduled_date, id) AS rn
                FROM public.study_plan_tasks
                WHERE plan_id = p_plan_id
                  AND status = 'pending'
                  AND scheduled_date < CURRENT_DATE
            ), free_days AS (
                SELECT
                    d::DATE AS schedule_date,
                    row_number() OVER (ORDER BY d::DATE) AS rn
                FROM generate_series(GREATEST(CURRENT_DATE, v_plan.start_date), v_plan.exam_date - 1, interval '1 day') d
                WHERE extract(dow FROM d)::SMALLINT = ANY(v_plan.study_weekdays)
                  AND NOT EXISTS (
                      SELECT 1 FROM public.study_plan_periods spp
                      WHERE spp.plan_id = p_plan_id
                        AND spp.mode = 'pause'
                        AND d::DATE BETWEEN spp.start_date AND spp.end_date
                  )
                  AND NOT EXISTS (
                      SELECT 1 FROM public.study_plan_tasks spt
                      WHERE spt.plan_id = p_plan_id
                        AND spt.scheduled_date = d::DATE
                        AND spt.status = 'pending'
                  )
            )
            UPDATE public.study_plan_tasks task
            SET scheduled_date = free_days.schedule_date,
                updated_at = timezone('utc'::text, now())
            FROM overdue
            JOIN free_days ON free_days.rn = overdue.rn
            WHERE task.id = overdue.id;

            GET DIAGNOSTICS v_moved = ROW_COUNT;
            RETURN jsonb_build_object('strategy', 'next_free_day', 'moved', v_moved, 'fallback', FALSE);
        END IF;
    END IF;

    v_moved := public.schedule_study_plan_pending(
        p_plan_id,
        GREATEST(CURRENT_DATE, v_plan.start_date)
    );
    RETURN jsonb_build_object('strategy', 'redistribute', 'moved', v_moved, 'fallback', v_strategy = 'next_free_day');
END;
$$;

REVOKE ALL ON FUNCTION public.rebalance_study_plan(UUID, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rebalance_study_plan(UUID, TEXT) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.get_study_plan_dashboard(p_bank_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
    v_plan public.study_plans%ROWTYPE;
    v_tasks JSONB := '[]'::jsonb;
    v_categories JSONB := '[]'::jsonb;
    v_periods JSONB := '[]'::jsonb;
    v_total INTEGER := 0;
    v_completed INTEGER := 0;
    v_due INTEGER := 0;
    v_overdue INTEGER := 0;
    v_completed_future INTEGER := 0;
    v_practiced INTEGER := 0;
    v_correct INTEGER := 0;
    v_answered INTEGER := 0;
    v_status TEXT := 'on_track';
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;
    IF NOT public.can_access_question_bank(p_bank_id) THEN
        RAISE EXCEPTION 'Question bank access denied';
    END IF;

    SELECT * INTO v_plan
    FROM public.study_plans
    WHERE user_id = auth.uid()
      AND question_bank_id = p_bank_id
      AND status = 'active'
    ORDER BY created_at DESC
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object(
            'bank_id', p_bank_id,
            'plan', NULL,
            'catalog', public.get_study_plan_catalog(p_bank_id)
        );
    END IF;

    SELECT
        COUNT(*)::INTEGER,
        COUNT(*) FILTER (WHERE status = 'completed')::INTEGER,
        COUNT(*) FILTER (WHERE scheduled_date <= CURRENT_DATE)::INTEGER,
        COUNT(*) FILTER (WHERE status = 'pending' AND scheduled_date < CURRENT_DATE)::INTEGER,
        COUNT(*) FILTER (WHERE status = 'completed' AND scheduled_date > CURRENT_DATE)::INTEGER
    INTO v_total, v_completed, v_due, v_overdue, v_completed_future
    FROM public.study_plan_tasks
    WHERE plan_id = v_plan.id;

    IF v_overdue > 0 THEN
        v_status := 'behind';
    ELSIF v_completed_future > 0 OR v_completed > v_due THEN
        v_status := 'ahead';
    ELSE
        v_status := 'on_track';
    END IF;

    SELECT COALESCE(jsonb_agg(task_payload ORDER BY scheduled_date, category_name, topic_name), '[]'::jsonb)
    INTO v_tasks
    FROM (
        SELECT
            spt.scheduled_date,
            COALESCE(ct.category, 'General') AS category_name,
            ct.name AS topic_name,
            jsonb_build_object(
                'id', spt.id,
                'topic_id', ct.id,
                'topic', ct.name,
                'category', COALESCE(ct.category, 'General'),
                'scheduled_date', spt.scheduled_date,
                'status', spt.status,
                'completed_at', spt.completed_at,
                'question_count', (
                    SELECT COUNT(*)::INTEGER
                    FROM public.question_topics qt
                    WHERE qt.question_bank_id = p_bank_id AND qt.topic_id = ct.id
                ),
                'article_id', (
                    SELECT tla.article_id
                    FROM public.topic_library_articles tla
                    WHERE tla.question_bank_id = p_bank_id AND tla.topic_id = ct.id
                    ORDER BY tla.is_primary DESC, tla.display_order, tla.article_id
                    LIMIT 1
                ),
                'exam_filters', COALESCE((
                    SELECT jsonb_agg(jsonb_build_object('category', f.category, 'topic', f.topic)
                        ORDER BY f.category, f.topic)
                    FROM (
                        SELECT DISTINCT q.category, q.topic
                        FROM public.question_topics qt
                        JOIN public.questions q ON q.id = qt.question_id
                        WHERE qt.question_bank_id = p_bank_id
                          AND qt.topic_id = ct.id
                          AND q.topic IS NOT NULL
                    ) f
                ), '[]'::jsonb),
                'session_id', (
                    SELECT spsl.session_id
                    FROM public.study_plan_session_links spsl
                    WHERE spsl.task_id = spt.id
                    ORDER BY spsl.created_at DESC
                    LIMIT 1
                )
            ) AS task_payload
        FROM public.study_plan_tasks spt
        JOIN public.content_topics ct ON ct.id = spt.topic_id
        WHERE spt.plan_id = v_plan.id
    ) task_rows;

    SELECT COALESCE(jsonb_agg(category_payload ORDER BY priority, category_name), '[]'::jsonb)
    INTO v_categories
    FROM (
        SELECT
            COALESCE(ct.category, 'General') AS category_name,
            COALESCE(spcp.priority, 100000) AS priority,
            jsonb_build_object(
                'category', COALESCE(ct.category, 'General'),
                'priority', COALESCE(spcp.priority, 100000),
                'total', COUNT(*),
                'completed', COUNT(*) FILTER (WHERE spt.status = 'completed'),
                'progress', CASE WHEN COUNT(*) = 0 THEN 0
                    ELSE ROUND((COUNT(*) FILTER (WHERE spt.status = 'completed')::NUMERIC / COUNT(*)::NUMERIC) * 100)
                END
            ) AS category_payload
        FROM public.study_plan_tasks spt
        JOIN public.content_topics ct ON ct.id = spt.topic_id
        LEFT JOIN public.study_plan_category_priorities spcp
          ON spcp.plan_id = v_plan.id
         AND spcp.category_name = COALESCE(ct.category, 'General')
        WHERE spt.plan_id = v_plan.id
        GROUP BY COALESCE(ct.category, 'General'), COALESCE(spcp.priority, 100000)
    ) category_rows;

    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'id', id, 'start_date', start_date, 'end_date', end_date, 'mode', mode
    ) ORDER BY start_date, id), '[]'::jsonb)
    INTO v_periods
    FROM public.study_plan_periods
    WHERE plan_id = v_plan.id;

    SELECT
        COUNT(DISTINCT ua.question_id)::INTEGER,
        COUNT(*) FILTER (WHERE ua.is_correct)::INTEGER,
        COUNT(*)::INTEGER
    INTO v_practiced, v_correct, v_answered
    FROM public.user_answers ua
    JOIN public.question_bank_questions qbq
      ON qbq.question_id = ua.question_id
     AND qbq.question_bank_id = p_bank_id
    WHERE ua.user_id = auth.uid();

    RETURN jsonb_build_object(
        'bank_id', p_bank_id,
        'plan', jsonb_build_object(
            'id', v_plan.id,
            'start_date', v_plan.start_date,
            'exam_date', v_plan.exam_date,
            'study_weekdays', v_plan.study_weekdays,
            'missed_strategy', v_plan.missed_strategy,
            'reduced_load_factor', v_plan.reduced_load_factor,
            'status', v_status,
            'total_topics', v_total,
            'completed_topics', v_completed,
            'progress', CASE WHEN v_total = 0 THEN 0 ELSE ROUND((v_completed::NUMERIC / v_total::NUMERIC) * 100) END,
            'questions_practiced', v_practiced,
            'qbank_accuracy', CASE WHEN v_answered = 0 THEN 0 ELSE ROUND((v_correct::NUMERIC / v_answered::NUMERIC) * 100) END,
            'periods', v_periods,
            'categories', v_categories,
            'tasks', v_tasks
        )
    );
END;
$$;

REVOKE ALL ON FUNCTION public.get_study_plan_dashboard(BIGINT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_study_plan_dashboard(BIGINT) TO authenticated, service_role;

COMMENT ON TABLE public.content_topics IS
    'Stable bank-scoped topic identity used by Study Plan, question mappings, and Library mappings. Category is metadata, not identity.';
COMMENT ON TABLE public.study_plans IS
    'User-owned bank-scoped preparation plan. One active plan per user/bank; older plans remain archived.';
COMMENT ON FUNCTION public.get_study_plan_dashboard(BIGINT) IS
    'Single read boundary for active Study Plan, topic completion, QBank practice summary, Library link, and exam filter resolution.';

-- Backfill any content already present when this migration is applied. Safe when the bank is empty.
SELECT public.refresh_content_topic_links(NULL);
