ALTER TABLE public.pathways FORCE ROW LEVEL SECURITY;
ALTER TABLE public.question_banks FORCE ROW LEVEL SECURITY;
ALTER TABLE public.blocks FORCE ROW LEVEL SECURITY;
ALTER TABLE public.questions FORCE ROW LEVEL SECURITY;
ALTER TABLE public.question_bank_questions FORCE ROW LEVEL SECURITY;
ALTER TABLE public.options FORCE ROW LEVEL SECURITY;
ALTER TABLE public.library_articles FORCE ROW LEVEL SECURITY;
