begin;

create table if not exists public.ai_deep_dive_config (
  id bigint generated by default as identity primary key,
  active boolean not null default true,
  primary_model text not null,
  fallback_model text,
  temperature numeric(4,3) not null default 0.2 check (temperature >= 0 and temperature <= 1),
  max_initial_tokens integer not null default 1800 check (max_initial_tokens between 300 and 4000),
  max_followup_tokens integer not null default 900 check (max_followup_tokens between 200 and 2500),
  prompt_version text not null default 'deep_dive_v1',
  timeout_ms integer not null default 30000 check (timeout_ms between 5000 and 55000),
  default_daily_limit integer not null default 4 check (default_daily_limit between 1 and 100),
  default_followup_limit integer not null default 12 check (default_followup_limit between 1 and 100),
  updated_at timestamptz not null default now()
);

create unique index if not exists ai_deep_dive_config_single_active
  on public.ai_deep_dive_config ((active))
  where active = true;

insert into public.ai_deep_dive_config (
  active,
  primary_model,
  fallback_model,
  temperature,
  max_initial_tokens,
  max_followup_tokens,
  prompt_version,
  timeout_ms,
  default_daily_limit,
  default_followup_limit
)
select
  true,
  'deepseek/deepseek-v4.1-flash',
  null,
  0.2,
  1800,
  900,
  'deep_dive_v1',
  30000,
  4,
  12
where not exists (
  select 1 from public.ai_deep_dive_config where active = true
);

create table if not exists public.ai_user_entitlements (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  daily_limit_override integer not null check (daily_limit_override between 1 and 1000),
  followup_limit_override integer not null check (followup_limit_override between 1 and 200),
  override_expires_at timestamptz,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_usage_events (
  event_id uuid primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid,
  thread_id uuid,
  question_id bigint,
  event_type text not null check (event_type in ('ai.deep_dive.started', 'ai.deep_dive.message')),
  model text,
  prompt_version text,
  cache_hit boolean not null default false,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  latency_ms numeric not null default 0 check (latency_ms >= 0),
  occurred_at timestamptz not null
);

create index if not exists ai_usage_events_user_time
  on public.ai_usage_events (user_id, occurred_at desc);

create index if not exists ai_usage_events_question_time
  on public.ai_usage_events (question_id, occurred_at desc)
  where question_id is not null;

create table if not exists public.ai_entitlement_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  daily_limit integer not null,
  followup_limit integer not null,
  expires_at timestamptz,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists ai_entitlement_audit_user_time
  on public.ai_entitlement_audit (user_id, created_at desc);

alter table public.ai_deep_dive_config enable row level security;
alter table public.ai_user_entitlements enable row level security;
alter table public.ai_usage_events enable row level security;
alter table public.ai_entitlement_audit enable row level security;

revoke all on table public.ai_deep_dive_config from anon, authenticated;
revoke all on table public.ai_user_entitlements from anon, authenticated;
revoke all on table public.ai_usage_events from anon, authenticated;
revoke all on table public.ai_entitlement_audit from anon, authenticated;

grant select, insert, update, delete on table public.ai_deep_dive_config to service_role;
grant select, insert, update, delete on table public.ai_user_entitlements to service_role;
grant select, insert, update, delete on table public.ai_usage_events to service_role;
grant select, insert, update, delete on table public.ai_entitlement_audit to service_role;

grant usage, select on all sequences in schema public to service_role;

commit;
