begin;

create table if not exists public.ai_royal_tutor_config (
  id bigint generated by default as identity primary key,
  active boolean not null default true,
  primary_model text not null default 'deepseek/deepseek-v4.1-flash',
  fallback_model text,
  temperature numeric(4,3) not null default 0.2 check (temperature >= 0 and temperature <= 1),
  max_output_tokens integer not null default 1200 check (max_output_tokens between 300 and 4000),
  prompt_version text not null default 'royal_ai_v1_grounded_chat',
  timeout_ms integer not null default 170000 check (timeout_ms between 5000 and 170000),
  default_daily_limit integer not null default 15 check (default_daily_limit between 1 and 1000),
  max_message_chars integer not null default 4000 check (max_message_chars between 500 and 12000),
  retrieval_candidates integer not null default 20 check (retrieval_candidates between 5 and 50),
  retrieval_final integer not null default 8 check (retrieval_final between 1 and 12),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_ai_royal_tutor_one_active
  on public.ai_royal_tutor_config ((active))
  where active = true;

insert into public.ai_royal_tutor_config(
  active, primary_model, fallback_model, temperature, max_output_tokens,
  prompt_version, timeout_ms, default_daily_limit, max_message_chars,
  retrieval_candidates, retrieval_final
)
select
  true,
  'deepseek/deepseek-v4.1-flash',
  'deepseek/deepseek-v4-pro-0813',
  0.2,
  1200,
  'royal_ai_v1_grounded_chat',
  170000,
  15,
  4000,
  20,
  8
where not exists (select 1 from public.ai_royal_tutor_config where active = true);

create table if not exists public.ai_royal_tutor_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  daily_limit integer not null check (daily_limit between 1 and 1000),
  expires_at timestamptz,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_royal_tutor_entitlement_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('set','clear')),
  daily_limit integer,
  expires_at timestamptz,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_royal_tutor_entitlement_audit_user
  on public.ai_royal_tutor_entitlement_audit(user_id, created_at desc);

create table if not exists public.ai_royal_tutor_usage_events (
  event_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null,
  request_id uuid not null,
  model text not null,
  prompt_version text not null,
  grounding_mode text not null check (grounding_mode in ('royal','general')),
  source_count integer not null default 0 check (source_count >= 0),
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  cost_usd numeric(18,10) not null default 0 check (cost_usd >= 0),
  retrieval_ms numeric not null default 0 check (retrieval_ms >= 0),
  first_token_ms numeric not null default 0 check (first_token_ms >= 0),
  generation_ms numeric not null default 0 check (generation_ms >= 0),
  total_ms numeric not null default 0 check (total_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_royal_tutor_usage_created
  on public.ai_royal_tutor_usage_events(created_at desc);
create index if not exists idx_ai_royal_tutor_usage_user
  on public.ai_royal_tutor_usage_events(user_id, created_at desc);
create index if not exists idx_ai_royal_tutor_usage_model
  on public.ai_royal_tutor_usage_events(model, created_at desc);

create table if not exists public.library_sources (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  publisher text,
  edition text,
  version text,
  source_date date,
  ai_search_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.library_articles
  add column if not exists source_id bigint references public.library_sources(id) on delete set null,
  add column if not exists ai_search_enabled boolean not null default true;

create index if not exists idx_library_articles_ai_search
  on public.library_articles(ai_search_enabled, source_id);

create table if not exists public.ai_royal_tutor_corpus_registry (
  article_id text primary key,
  object_key text not null unique,
  content_hash text not null,
  published_at timestamptz not null default now()
);

alter table public.ai_royal_tutor_config enable row level security;
alter table public.ai_royal_tutor_entitlements enable row level security;
alter table public.ai_royal_tutor_entitlement_audit enable row level security;
alter table public.ai_royal_tutor_usage_events enable row level security;
alter table public.library_sources enable row level security;
alter table public.ai_royal_tutor_corpus_registry enable row level security;

revoke all on table public.ai_royal_tutor_config from anon, authenticated;
revoke all on table public.ai_royal_tutor_entitlements from anon, authenticated;
revoke all on table public.ai_royal_tutor_entitlement_audit from anon, authenticated;
revoke all on table public.ai_royal_tutor_usage_events from anon, authenticated;
revoke all on table public.library_sources from anon, authenticated;
revoke all on table public.ai_royal_tutor_corpus_registry from anon, authenticated;

grant all on table public.ai_royal_tutor_config to service_role;
grant all on table public.ai_royal_tutor_entitlements to service_role;
grant all on table public.ai_royal_tutor_entitlement_audit to service_role;
grant all on table public.ai_royal_tutor_usage_events to service_role;
grant all on table public.library_sources to service_role;
grant all on table public.ai_royal_tutor_corpus_registry to service_role;

create or replace function public.admin_get_royal_ai_overview_session(
  p_from timestamptz default (now() - interval '30 days')
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_config jsonb;
  v_usage jsonb;
  v_models jsonb;
begin
  if auth.uid() is null or not exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_active = true and p.role = 'admin'
  ) then
    raise exception 'Admin access is required.' using errcode = '42501';
  end if;

  select to_jsonb(c) - 'id' - 'active' - 'created_at'
    into v_config
  from public.ai_royal_tutor_config c
  where c.active = true
  limit 1;

  select jsonb_build_object(
    'messages', count(*),
    'active_users', count(distinct user_id),
    'royal_grounded', count(*) filter (where grounding_mode = 'royal'),
    'general_fallback', count(*) filter (where grounding_mode = 'general'),
    'grounded_rate_percent',
      case when count(*) = 0 then 0
           else round(100.0 * count(*) filter (where grounding_mode = 'royal') / count(*), 2)
      end,
    'input_tokens', coalesce(sum(input_tokens), 0),
    'output_tokens', coalesce(sum(output_tokens), 0),
    'cost_usd', coalesce(sum(cost_usd), 0),
    'avg_retrieval_ms', coalesce(avg(retrieval_ms), 0),
    'avg_first_token_ms', coalesce(avg(first_token_ms), 0),
    'avg_total_ms', coalesce(avg(total_ms), 0)
  )
  into v_usage
  from public.ai_royal_tutor_usage_events
  where created_at >= p_from;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.requests desc), '[]'::jsonb)
  into v_models
  from (
    select
      model,
      count(*) as requests,
      coalesce(sum(input_tokens), 0) as input_tokens,
      coalesce(sum(output_tokens), 0) as output_tokens,
      coalesce(sum(cost_usd), 0) as cost_usd
    from public.ai_royal_tutor_usage_events
    where created_at >= p_from
    group by model
  ) x;

  return jsonb_build_object(
    'from', p_from,
    'to', now(),
    'config', coalesce(v_config, '{}'::jsonb),
    'usage', coalesce(v_usage, '{}'::jsonb),
    'models', coalesce(v_models, '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_update_royal_ai_config_session(
  p_primary_model text,
  p_fallback_model text,
  p_temperature numeric,
  p_max_output_tokens integer,
  p_timeout_ms integer,
  p_default_daily_limit integer,
  p_max_message_chars integer,
  p_retrieval_candidates integer,
  p_retrieval_final integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_updated_at timestamptz := now();
  v_rows integer;
begin
  if auth.uid() is null or not exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_active = true and p.role = 'admin'
  ) then
    raise exception 'Admin access is required.' using errcode = '42501';
  end if;

  if length(trim(p_primary_model)) < 3
     or p_temperature < 0 or p_temperature > 1
     or p_max_output_tokens not between 300 and 4000
     or p_timeout_ms not between 5000 and 170000
     or p_default_daily_limit not between 1 and 1000
     or p_max_message_chars not between 500 and 12000
     or p_retrieval_candidates not between 5 and 50
     or p_retrieval_final not between 1 and 12
     or p_retrieval_final > p_retrieval_candidates then
    raise exception 'Invalid Royal AI configuration.' using errcode = '22023';
  end if;

  update public.ai_royal_tutor_config
  set primary_model = trim(p_primary_model),
      fallback_model = nullif(trim(coalesce(p_fallback_model, '')), ''),
      temperature = p_temperature,
      max_output_tokens = p_max_output_tokens,
      timeout_ms = p_timeout_ms,
      default_daily_limit = p_default_daily_limit,
      max_message_chars = p_max_message_chars,
      retrieval_candidates = p_retrieval_candidates,
      retrieval_final = p_retrieval_final,
      updated_at = v_updated_at
  where active = true;

  get diagnostics v_rows = row_count;
  if v_rows <> 1 then
    raise exception 'Active Royal AI configuration was not found.' using errcode = 'P0001';
  end if;

  return jsonb_build_object('updated_at', v_updated_at);
end;
$$;

revoke all on function public.admin_get_royal_ai_overview_session(timestamptz) from public, anon;
grant execute on function public.admin_get_royal_ai_overview_session(timestamptz) to authenticated;

revoke all on function public.admin_update_royal_ai_config_session(
  text,text,numeric,integer,integer,integer,integer,integer,integer
) from public, anon;
grant execute on function public.admin_update_royal_ai_config_session(
  text,text,numeric,integer,integer,integer,integer,integer,integer
) to authenticated;

commit;
